{
 "title": "Anomaly_Detection_SDN V2.3",
 "description": "METRIC ANOMALY DETECTION SDN",
 "time": { "from": "2024-11-13T11:01:00.000Z", "to": "2024-11-13T11:15:00.000Z" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Postgres", "query": "grafana-postgresql-datasource" },
   {
    "name": "host_hostname_1",
    "label": "Host Name",
    "query": "select distinct(host_hostname) from anomaly_detection.anomaly_detection_score_sdn_2  order by host_hostname limit 800;"
   },
   {
    "name": "sysdig_metrics",
    "label": "Univariate Sysdig Metrics",
    "query": "SELECT column_name FROM information_schema.columns \nWHERE table_name = 'anomaly_detection_score_sdn_2' \nAND (column_name LIKE 'fabcon%' OR column_name IN ( 'sysdig_host_net_tcp_queue_len',\n       'sysdig_container_net_total_bytes',\n       'sysdig_container_net_tcp_queue_len',\n       'sysdig_container_memory_limit_used_percent',\n       'fabcon_iob_st_stats_DroppedPktsTotal', 'fabcon_nat_DroppedPktsTotal',\n       'sysdig_program_cpu_cores_used_percent',\n'fabcon_iob_fw_stats_SummaryPortMetricsInsertToHashFailureCounter'))"
   },
   {
    "name": "top_variables",
    "label": "Top Variables",
    "query": "select * from anomaly_detection.anomaly_detection_multivariate_loadings_sdn_1 order by level_0 desc limit 1;"
   },
   {
    "name": "kube_namespace",
    "label": "Kube Namespace",
    "query": "SELECT DISTINCT kube_namespace_name\nFROM anomaly_detection.anomaly_detection_score_sdn_2\nWHERE TRIM(kube_namespace_name) <> '';"
   },
   {
    "name": "host_hostname_2",
    "label": "Host Hostname 2",
    "query": "SELECT host_hostname\nFROM (\n    SELECT DISTINCT(host_hostname)\n    FROM anomaly_detection.anomaly_detection_score_sdn_2\n    ORDER BY host_hostname\n    LIMIT 800\n    OFFSET 800\n) AS subquery\nUNION\nSELECT 'qz'\nWHERE NOT EXISTS (\n    SELECT DISTINCT(host_hostname)\n    FROM anomaly_detection.anomaly_detection_score_sdn_2\n    ORDER BY host_hostname\n    LIMIT 800\n    OFFSET 800\n);\n"
   },
   {
    "name": "sysdig_metrics_multivariant",
    "label": "Multivariant Sysdig Metrics",
    "query": "SELECT column_name FROM information_schema.columns \nWHERE table_name = 'anomaly_detection_score_multivariate_sdn_2' \nAND (column_name LIKE 'fabcon%' OR column_name IN ( 'sysdig_host_net_tcp_queue_len',\n       'sysdig_container_net_total_bytes',\n       'sysdig_container_net_tcp_queue_len',\n       'sysdig_container_memory_limit_used_percent',\n       'fabcon_iob_st_stats_DroppedPktsTotal', 'fabcon_nat_DroppedPktsTotal',\n       'sysdig_program_cpu_cores_used_percent',\n'fabcon_iob_fw_stats_SummaryPortMetricsInsertToHashFailureCounter'))"
   },
   { "name": "kube_pod_name", "label": "Kube Pod Name" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n  <h1 style=\"color: #ffffff; background-color: #3b5998; font-family: 'Arial', sans-serif; padding: 20px; text-align: center; border-radius: 10px; box-shadow: 2px 2px 15px rgba(0, 0, 0, 0.1);\">\n    Anomaly Detection Dashboard\n  </h1>\n\n"
   }
  },
  {
   "title": "Univariate Anomaly Detection (Mzone727)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Anomalies Detected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(anomaly_label) AS \"Anomaly Count\"\n  -- COUNT(anomaly_label) AS \"Total Records\"\nFROM\n  anomaly_detection.anomaly_detection_score_sdn_2\nWHERE\n  anomaly_label IN (1,0)\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  );\n\n\n--   AND time >= extract(epoch from to_timestamp($__timeFrom(), 'YYYY-MM-DD\"T\"HH24:MI:SS.Z'))\n--   AND time <= extract(epoch from to_timestamp($__timeTo(), 'YYYY-MM-DD\"T\"HH24:MI:SS.Z'))\n-- GROUP BY time\n-- ORDER BY time\n"
    }
   ]
  },
  {
   "title": "Sysdig Metrics Anomalies Details",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\nto_timestamp(time) as time,\n-- kube_node_name,\n-- kube_cluster_name,\n-- agent_tag_cluster,\n-- agent_tag_cluster_type,\n-- host_hostname,\n-- kube_namespace_name,\n-- kube_workload_name,\n-- kube_pod_name,\n${sysdig_metrics:raw}\nFROM\n  anomaly_detection.anomaly_detection_score_sdn_2\nWHERE \n  anomaly_label in (0,1)\n  -- anomaly_label = 1\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  )\n  ORDER BY\n  time ASC;\n-- SELECT \n--   to_timestamp(timestamp) AS time, \n--    ${sysdig_metrics:raw}\n-- FROM \n--   anomaly_detection.anomaly_detection_score_sdn_2\n-- WHERE \n--   anomaly_label = 1;\n"
    }
   ]
  },
  {
   "title": "Metric Median Values",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  median_value AS \"Median Values\",\n  sysdig_metric AS \"Sysdig Metric\"\nFROM\n  anomaly_detection.anomaly_detection_univarient_sysdig_metrics_median_values\nWHERE\n  sysdig_metric IN ($sysdig_metrics);\n"
    }
   ]
  },
  {
   "title": "Total Records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(anomaly_label) AS \"Total Records\"\nFROM\n  anomaly_detection.anomaly_detection_score_sdn_2\nWHERE\n  anomaly_label IN (1,0)\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  );\n"
    }
   ]
  },
  {
   "title": "Anomalies Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\nto_timestamp(\"time\") AT TIME ZONE 'UTC' AS \"Time\",\n \"kube_node_name\" AS \"Kube Node Name\",\n\"kube_cluster_name\" as \"Kube Cluster Name\",\n\"agent_tag_cluster\" as \"Agent Tag Cluster\",\n\"agent_tag_cluster_type\" as \"Agent Tag Cluster Type\",\n\"host_hostname\" as \"Host Name\",\nkube_namespace_name as \"Kube Name Space\",\n\"kube_workload_name\" as \"Kube Workload Name\",\n\"kube_pod_name\" as \"Kube Pod Name\",\n${sysdig_metrics:raw}\nFROM\n  anomaly_detection.anomaly_detection_score_sdn_2\nWHERE \n  anomaly_label = 1\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  );\n"
    }
   ]
  },
  {
   "title": "Multivariate Anomaly Detection (Mzone727)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Anomalies Detected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(anomaly_label) AS \"Anomaly Count\"\nFROM\n  anomaly_detection.anomaly_detection_score_multivariate_sdn_2\nWHERE\n  anomaly_label IN (1,0)\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  );\n\n\n"
    }
   ]
  },
  {
   "title": "Total Records",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(anomaly_label) as \"Total Records\" \nFROM\n  anomaly_detection.anomaly_detection_score_multivariate_sdn_2\nWHERE\n  anomaly_label IN (1,0)\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  );\n\n\n\n"
    }
   ]
  },
  {
   "title": "Top Impacted Hosts",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  host_hostname as \"Host Name\",\n  kube_namespace_name as \"Kube Name Space\",\n  kube_workload_name as \"Kube Work Load Name\",\n  kube_pod_name as \"Kube Pod Name\",\n  count(anomaly_label) as \"Anomaly Count\"\nFROM\n  anomaly_detection.anomaly_detection_score_multivariate_sdn_2\nWHERE\n  anomaly_label = 1\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  )\n  GROUP BY  host_hostname,\n  kube_namespace_name,\n  kube_workload_name,\n  kube_pod_name\nORDER BY \"Anomaly Count\" DESC"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  host_hostname as \"Host Name\",\n  -- kube_namespace_name,\n  -- kube_workload_name,\n  -- kube_pod_name,\n  count(anomaly_label) as \"Anomaly Count\"\nFROM\n  anomaly_detection.anomaly_detection_score_multivariate_sdn_2\nWHERE\n  anomaly_label = 1\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  )\n  GROUP BY  host_hostname\n  -- kube_namespace_name,\n  -- kube_workload_name,\n  -- kube_pod_name\nORDER BY \"Anomaly Count\" DESC"
    }
   ]
  },
  {
   "title": "Top Metrics Causing Anonaly",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "options": {
    "content": "<div>\n  <!-- <h2>Top Metrics</h2> -->\n  <ul>\n  {{{data.[0].index}}}\n  </ul>\n</div>"
   },
   "targets": [
    {
     "rawSql": "-- SELECT index FROM anomaly_detection.anomaly_detection_multivariate_loadings_sdn_1\n-- order by level_0 desc LIMIT 1;\n\n\nSELECT index FROM anomaly_detection.anomaly_detection_multivariate_loadings_sdn_1\norder by index desc LIMIT 1;"
    }
   ]
  },
  {
   "title": "Metric Based Anomalies Detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  host_hostname,\n  kube_namespace_name,\n  kube_workload_name,\n  kube_pod_name,\n  ${sysdig_metrics_multivariant:raw}\nFROM\n  anomaly_detection.anomaly_detection_score_multivariate_sdn_2\nWHERE\n  anomaly_label = 1\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Anomalies Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"Time\",\n  host_hostname as \"Host Name\",\n  kube_namespace_name as \"Kube Name Space\",\n  kube_workload_name as \"Kube Work Load Name\",\n  kube_pod_name as \"Kube Pod Name\",\n  ${sysdig_metrics_multivariant:raw}\nFROM\n  anomaly_detection.anomaly_detection_score_multivariate_sdn_2\nWHERE\n  anomaly_label = 1\n  AND (\n    COALESCE('${kube_pod_name:raw}', '') = '' OR kube_pod_name = '${kube_pod_name:raw}'\n  )\n  AND (\n    (\n      host_hostname IN ($host_hostname_1) OR\n      host_hostname IN ($host_hostname_2) OR\n      host_hostname IS NULL\n    )\n    AND (\n      kube_namespace_name IN ($kube_namespace) OR\n      kube_namespace_name IS NULL\n    )\n  )\n    -- AND time >= extract(epoch from to_timestamp($__timeFrom(), 'YYYY-MM-DD\"T\"HH24:MI:SS.Z'))\n  -- AND time <= extract(epoch from to_timestamp($__timeTo(), 'YYYY-MM-DD\"T\"HH24:MI:SS.Z'))\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Sysdig Events & Notifications (DAL us-south production Sysdig)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) AS \"Total Events in last 1 hour\",\n  \"timestamp\" as time\nFROM\n  anomaly_detection.sysdig_events \nGROUP BY timestamp\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE \n    WHEN COUNT(id) > 1 THEN COUNT(id)\n    ELSE 0\n  END AS \"Total Active Notifications in last 24 hour\",\n  \"timestamp\" as time\nFROM\n  anomaly_detection.sysdig_notifications\n  GROUP BY timestamp\n"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(name) as \"Counts\", name as \"Name\"\nFROM anomaly_detection.sysdig_events\nGROUP BY \"Name\"\norder by \"Counts\" desc"
    }
   ]
  },
  {
   "title": "Top 10 Sysdig Notifications",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT \"alertName\" as \"Alert Name\", count(\"alertName\") as \"Notification Count\"\nFROM anomaly_detection.sysdig_notifications \nGROUP BY \"alertName\"\norder by \"Notification Count\" desc\nlimit 10;"
    }
   ]
  },
  {
   "title": "Top Impacted Hosts(Last 1 hour)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT scope as \"Scope\", COUNT(scope) as \"Event Counts\"\nFROM anomaly_detection.sysdig_events\nGROUP BY \"Scope\"\norder by \"Event Counts\" desc"
    }
   ]
  },
  {
   "title": "Notifications Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(\"timestamp\"/1000000) as \"Time\", kube_cluster_name as \"Kube Cluster Name\", kube_pod_name as \"Kube Pod Name\", \"alertName\", severity\nFROM anomaly_detection.sysdig_notifications \norder by severity asc"
    }
   ]
  }
 ]
}